version: '3'

services: 
  backend-node:
    image: emoket/backend-node:1.0.0
    ports:
      - 8083:8083
  backend-spring:
    image: emoket/backend-spring:1.0.0
    ports:
      - 8082:8082
  bff:
    image: emoket/bff:1.0.0
    depends_on:
      - backend-spring
      - backend-node
    ports:
      - 8081:8081
    environment:
      - BACKEND_SPRING_HOST=backend-spring
      - BACKEND_SPRING_PORT=8082
      - BACKEND_NODE_HOST=backend-node
      - BACKEND_NODE_PORT=8083
  frontend-vue:
    image: emoket/frontend-vue:1.0.0
    ports:
      - 8080:8080
