apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bff
  labels:
    appName: greeting
    svcName: bff 
    version: 1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      appName: greeting
      svcName: bff 
      version: 1.0.0
  template:
    metadata:
      labels:
        appName: greeting
        svcName: bff 
        version: 1.0.0
    spec:
      containers:
      - name: bff
        image: "emoket/bff:1.0.0"
        imagePullPolicy: Always
        env:
          - name: target.backend.spring.name
            value: "backend-spring"
          - name: target.backend.node.name
            value: "backend-node"
        ports:
          - name: default
            containerPort: 8081
            protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /actuator/health
#            port: default
#          initialDelaySeconds: 10
#          periodSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /actuator/health
#            port: default
#          initialDelaySeconds: 10
#          periodSeconds: 10

