apiVersion: v1
kind: Service
metadata:
  name: service-bff
  labels:
    appName: greeting
    svcName: bff
    version: 1.0.0
spec:
  type: ClusterIp
  ports:
  - name: default
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    appName: greeting
    svcName: bff
    version: 1.0.0
