apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backend-spring
  labels:
    appName: greeting
    svcName: backend-spring
    version: 1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      appName: greeting
      svcName: backend-spring
      version: 1.0.0
  template:
    metadata:
      labels:
        appName: greeting
        svcName: backend-spring
        version: 1.0.0
    spec:
      containers:
      - name: backend-spring
        image: "emoket/backend-spring:1.0.0"
        imagePullPolicy: Always
        ports:
          - name: default
            containerPort: 8082
            protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /actuator/health
#            port: default
#          initialDelaySeconds: 10
#          periodSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /actuator/health
#            port: default
#          initialDelaySeconds: 10
#          periodSeconds: 10

