apiVersion: v1
kind: Service
metadata:
  name: service-backend-spring
  labels:
    appName: greeting
    svcName: backend-spring
    version: 1.0.0
spec:
  type: ClusterIP
  ports:
  - name: default
    protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    appName: greeting
    svcName: backend-spring
    version: 1.0.0
