apiVersion: v1
kind: Service
metadata:
  name: backend-spring-service
spec:
  selector:
    app: backend-spring
  type: ClusterIP
  ports:
  - name: default
    protocol: TCP
    port: 8082
    targetPort: 8082
